services:
  backend:
    build:
      context: .
      dockerfile: example/Dockerfile
    container_name: nggorpc-backend
    ports:
      - "8080:8080"
    networks:
      - nggorpc-network

  frontend:
    build:
      context: .
      dockerfile: demo-app/Dockerfile
    container_name: nggorpc-frontend
    ports:
      - "8352:80"
    networks:
      - nggorpc-network
    depends_on:
      backend:
        condition: service_started

  e2e:
    build:
      context: ./e2e-tests
      dockerfile: Dockerfile
    container_name: nggorpc-e2e
    networks:
      - nggorpc-network
    environment:
      - BASE_URL=http://frontend:80
      - CI=true
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started
    volumes:
      - ./e2e-tests/tests:/app/tests
      - ./e2e-tests/playwright.config.ts:/app/playwright.config.ts
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  nggorpc-network:
    driver: bridge
