version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: example/Dockerfile
    container_name: nggorpc-backend
    ports:
      - "8080:8080"
    networks:
      - nggorpc-network

  frontend:
    build:
      context: .
      dockerfile: demo-app/Dockerfile
    container_name: nggorpc-frontend
    ports:
      - "8352:80"
    networks:
      - nggorpc-network
    depends_on:
      backend:
        condition: service_started

networks:
  nggorpc-network:
    driver: bridge
